version: '3.1'
services:
  grpc:
    image: grpc-spring-boot-starter-native-demo:4.5.2-SNAPSHOT
    environment:
      - SPRING_CLOUD_CONSUL_ENABLED=false
      - SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED=false
      - SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED=false
      - SPRING_CLOUD_CONSUL_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED=false
    ports:
      - "6565:6565"
